<?php

/**
 * Implements hook_theme().
 */
function d500px_theme() {
  return array(
    'd500px_photo' => array(
      'variables' => array('photo' => NULL),
    ),
    'd500px_photos' => array(
      'variables' => array('photos' => NULL),
    ),
  );
}

function d500px_preprocess_d500px_photo(array &$variables) {
  $variables['photo']['#theme'] = 'image';
  $variables['photo']['#style_name'] = NULL;
}
