<?php

/**
 * Implements hook_theme().
 */
function d500px_block_theme() {
  return array(
    'd500px_block_photo' => array(
      'variables' => array(),
    ),
    'd500px_block_photos' => array(
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_requirements().
 */
//function d500px_block_requirements() {
  // TODO Add hook_requirements to check if
  // Api keys and other settings have been set.
//}
