<?php


/**
 * implimentation of hook_form_FORM_ID_alter()
 */
function d500px_blocks_form_d500px_admin_form_alter(&$form, &$form_state, $form_id) {

  $form['d500px_blocks'] = array(
    '#type' => 'fieldset', 
    '#title' => t('500px Block Config'), 
    '#collapsible' => FALSE, 
    '#collapsed' => FALSE,
  );

  $form['d500px_blocks']['d500px_blocks_number_blocks'] = array(
    '#type'               => 'select', 
    '#title'              => t('Number of blocks required?'),
    '#options'            => array_combine(range(1,20),range(1,20)),
    '#default_value'      => variable_get('d500px_blocks_number_blocks', 1),
    '#description'        => t('The number of blocks can be increased or decreased at any time. Default is 1 block.'),
    //'#required'           => TRUE,
  );  
  
}